import { create } from 'zustand'

const useStore = create((set) => ({
  publicKey: null,
  balance: null,
  walletName: '',
  status: '',
  txHash: '',
  isSending: false,
  amount: '',
  totalRaised: '0',
  goal: '0',
  deadline: 0,
  recentDonors: [],
  donationCount: 0,
  campaigns: [],
  selectedCampaign: null,
  isLoadingCampaigns: false,
  showCreateForm: false,

  setPublicKey: (publicKey) => set({ publicKey }),
  setBalance: (balance) => set({ balance }),
  setWalletName: (walletName) => set({ walletName }),
  setStatus: (status) => set({ status }),
  setTxHash: (txHash) => set({ txHash }),
  setIsSending: (isSending) => set({ isSending }),
  setTotalRaised: (totalRaised) => set({ totalRaised }),
  setGoal: (goal) => set({ goal }),
  setDeadline: (deadline) => set({ deadline }),
  setRecentDonors: (recentDonors) => set({ recentDonors }),
  setDonationCount: (donationCount) => set({ donationCount }),
  setAmount: (amount) => set({ amount }),
  setCampaigns: (campaigns) => set({ campaigns }),
  setSelectedCampaign: (selectedCampaign) => set({ selectedCampaign }),
  setIsLoadingCampaigns: (isLoadingCampaigns) => set({ isLoadingCampaigns }),
  setShowCreateForm: (showCreateForm) => set({ showCreateForm }),
  resetWallet: () => set({ publicKey: null, balance: null, walletName: '', amount: '', selectedCampaign: null }),
  resetTx: () => set({ status: '', txHash: '' }),
}))

export default useStore
